### ISSUE TITLE
Add support for BigQuery Scheduled Queries

### ISSUE THREAD

**Issue by cemo** [GoogleCloudPlatform/magic-modules#1628] opened 2019-04-06 13:46 UTC
Add support for BigQuery Scheduling Queries. It is very crucial to complement some missing parts of BigQuery to create workarounds.

**Comment by rileykarson** [comment] 2019-04-22 23:13
Hey @cemo! Generally, we try to file bugs against specific tools' repos. Which are you interested in support for?

**Comment by cemo** [comment] 2019-04-22 23:16
Hey, terraform :)

**Comment by rileykarson** [comment] 2019-04-23 14:30
Closing this as a dupe of the provider-specific issue: https://github.com/terraform-providers/terraform-provider-google/issues/2028

**Closed by rileykarson** 2019-04-23 14:30 UTC
