### ISSUE TITLE
[ansible] no error is shown if api is disabled

### ISSUE THREAD

**Issue by JSchlarb** [GoogleCloudPlatform/magic-modules#663] opened 2018-11-01 15:59 UTC
Due the fact that the 403 status code is suppressed it leads to false positive (e. g. Api is not enabled). Would be awesome if someone can share the intention behind. .

 https://github.com/GoogleCloudPlatform/magic-modules/blob/a7f732f3f82d914e9bc7859abd920990be319bd7/products/sql/helpers/ansible/return_if_object.py#L9-L11

https://github.com/ansible/ansible/issues/45547

**Comment by rambleraptor** [comment] 2018-11-02 18:36
Hello! Thanks for filling this. Unfortunately, the Cloud SQL API has a quirk where, if you try to get information about a database that does not exist, it returns a 403 (not a 404 as intended). We have to skip 403s in this case. We'll figure out a better way to message this.

**Comment by rileykarson** [comment] 2019-03-07 18:29
Hey @JSchlarb!

We're closing issues against specific tools MM generates; they should be tracked in the appropriate repo for that tool. For our Ansible integrations, that means [against the ansible/ansible repo](https://github.com/ansible/ansible/issues/new/choose). If you've already filed an issue there, that's the best way to track fixes; otherwise, by filing there it will be assigned to the right person.

**Closed by rileykarson** 2019-03-07 18:29 UTC
