### ISSUE TITLE
Generate operation handlers across products

### ISSUE THREAD

**Issue by danawillow** [GoogleCloudPlatform/magic-modules#203] opened 2018-05-18 00:20 UTC
Right now, we still write `___operation.go` files by hand, but we can probably generate them too.

- [x] Terraform
- [ ] Ansible

**Comment by danawillow** [comment] 2018-08-24 17:33
@rileykarson @chrisst fyi this might be an interesting thing to look at if you end up with a spare moment. Fair warning: the async files as they are make some very strong assumptions about the shape of the Operation objects which are very much not true, so it's possible they'd have to be rewritten. This is definitely a hard task, but it would be really really nice to have.

**Comment by rileykarson** [comment] 2019-07-24 20:30
@rambleraptor- are these generated in Ansible?

It's possible in Terraform now, and around 60% of existing products can be supported. We'll need to add overrides/config for the rest, but it's enough to close this issue out on Terraform's behalf imo.

**Comment by rambleraptor** [comment] 2019-07-24 20:37
Ansible is generating all asynchronous operations.

I was able to generate ML Models on Terraform using the built in support I built a while back, so it seems like TF is working as intended.

**Comment by rileykarson** [comment] 2019-07-24 21:05
Yeah, we expect it to work for newer APIs that are more standardised but it needs some tweaking for older ones. Closing out since we have general support.

**Closed by rileykarson** 2019-07-24 21:05 UTC
Labels: enhancement, magic-modules
